version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "80:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: example_password
    depends_on:
      - mariadb
    networks:
      - my-network

  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/example_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=example_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - my-network
    depends_on:
      - mariadb

networks:
  my-network:
    driver: bridge
